### ISSUE TITLE
Streamline Actions Setup

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#110]
### Goal

Simplify and clarify the configuration of our GitHub Actions:

1. Drop unnecessary specifications such as `container` (the default setup works).
2. Align setup with conventions, e.g. use standard python setup rather than creating virtualenv on our own.
3. Add a short explanation at the top of the script such that new users quickly understand what the script does. Similar as a module doc string in a python module
4. Use clear names for files, (job) name, steps, etc.

### Context

Here's a streamline GitHub Action configuration from another one of our projects:
```yaml
# ---------------------------------------------------------------------------------
# Reconciliation and Coherence Check
#
# Compare expected account balances in the `reconciliation` folder with actual
# account balances in the accounting system.
# ---------------------------------------------------------------------------------

name: Reconcile

on:
  push:
  schedule:
    - cron: "0 5 * * *"

jobs:
  reconcile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install pyledger
        run: pip install https://github.com/macxred/pyledger/tarball/production

      - name: Run ledger reconcile
        run: ledger -c company_name reconcile
```
